char *gcalloc(ulong, long**);
char *gcrealloc(char*, ulong);
void shiftgcarena(ulong nl);
void gcfree(char *cp);
static void compact(void);
void Bcopy(char*, char*, char*, int);
void gcchk(void);
char *charstar();
char *jerqname();
long min(int, int);
void mesg(char*, char*);
void panic(char*);
void allocinit(void);
char *alloc(ulong);
void free(void*);
void allocerr(void);
void *malloc(unsigned);
void namecompact(char *, char *);
void rescue(int);
void message(void);
char *skipbl(char *p);
void commands(File *f);
void checkifdups(File *f);
void writechanged(void);
char *data2(int n);
long labs(long a);
void moveto(File *f, long p1, long p2);
void tellseek(File *f);
void error(char *s, char *t);
void quit(char *s);
void ioerr(char *s, char *t);
void mesg(char *s, char *t);
void sendstr(unsigned f, int op, int posn, char *d);
void dprint(char *a, ...);
void panic(char *s);
int boot(char *s);
int System(char *s, char *t, char *u, char *v);
void modified(File *f);
void unmodified(File *f);
